# Generated by Django 5.2.4 on 2025-08-05 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usersubject_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('ADMIN', 'Админ'), ('DIRECTOR', 'Директор'), ('HEAD_TEACHER', 'Завуч'), ('AUDITOR', 'Аудитор'), ('TEACHER', 'Учитель'), ('PARENT', 'Родитель'), ('STUDENT', 'Ученик')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
