# Generated by Django 5.2.4 on 2025-08-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_holiday_academicyear_end_date_and_more'),
        ('ktp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('topic_order', models.PositiveIntegerField(blank=True, null=True)),
                ('topic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('TEMPLATE', 'Template'), ('MANUAL', 'Manual'), ('IMPORT', 'Import')], default='TEMPLATE', max_length=16)),
                ('template_week_id', models.IntegerField(blank=True, null=True)),
                ('template_lesson_id', models.IntegerField(blank=True, null=True)),
                ('generation_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('conducted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grade')),
                ('ktp_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktp.ktpentry')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lessontype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('JITSI', 'Jitsi'), ('BBB', 'Bbb'), ('ZOOM', 'Zoom')], max_length=16)),
                ('join_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='real_schedule.reallesson')),
            ],
        ),
        migrations.AddIndex(
            model_name='reallesson',
            index=models.Index(fields=['grade', 'start'], name='real_schedu_grade_i_e9be12_idx'),
        ),
        migrations.AddIndex(
            model_name='reallesson',
            index=models.Index(fields=['teacher', 'start'], name='real_schedu_teacher_58787b_idx'),
        ),
        migrations.AddIndex(
            model_name='reallesson',
            index=models.Index(fields=['source', 'start'], name='real_schedu_source_d9580d_idx'),
        ),
    ]
