# Generated by Django 5.2.6 on 2025-09-07 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('+', 'Присутствовал'), ('-', 'Отсутствовал'), ('late', 'Опоздал')], max_length=4, null=True)),
                ('late_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mark', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_students', to='real_schedule.reallesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['lesson', 'student'], name='real_schedu_lesson__640484_idx')],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
