# Generated by Django 5.2.6 on 2025-09-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_schedule', '0002_lessonstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='provider',
        ),
        migrations.AddField(
            model_name='room',
            name='auto_manage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='jitsi_domain',
            field=models.CharField(default='jitsi.school.edu', max_length=128),
        ),
        migrations.AddField(
            model_name='room',
            name='jitsi_env',
            field=models.CharField(default='SELF_HOSTED', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_duration_secs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_status',
            field=models.CharField(default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='recording_storage',
            field=models.CharField(default='LOCAL', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('MEETING', 'Meeting')], default='LESSON', max_length=16),
        ),
        migrations.AlterField(
            model_name='room',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='real_schedule.reallesson'),
        ),
    ]
