# Generated by Django 5.2.6 on 2025-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_schedule', '0004_populate_jitsi_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reallesson',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
