# Generated by Django 5.2.4 on 2025-07-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_academicyear_options_alter_grade_options_and_more'),
        ('template', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelesson',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='core.lessontype'),
        ),
    ]
