# Generated by Django 5.2.4 on 2025-07-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklynorm',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
        ),
        migrations.AddField(
            model_name='weeklynorm',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklynorm',
            unique_together={('grade', 'subject')},
        ),
    ]
