# Generated by Django 5.2.4 on 2025-07-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usersubject_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklynorm',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'Недельные нормы', 'verbose_name_plural': 'Недельные нормы'},
        ),
    ]
