# Generated by Django 5.2.4 on 2025-07-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_weeklynorm_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'Тип урока', 'verbose_name_plural': 'Типы уроков'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['teacher', 'day_of_week', 'start_time'], 'verbose_name': 'Доступность учителя', 'verbose_name_plural': 'Доступность учителей'},
        ),
        migrations.AlterModelOptions(
            name='weeklynorm',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'Недельная норма', 'verbose_name_plural': 'Недельные нормы'},
        ),
    ]
