# Generated by Django 5.2.4 on 2025-07-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_academicyear_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklynorm',
            name='hours_per_week',
        ),
    ]
