# Generated by Django 5.2.4 on 2025-07-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_weeklynorm_hours_per_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'AcademicYear', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='gradesubject',
            options={'verbose_name': 'GradeSubject', 'verbose_name_plural': 'Класс–предмет'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'LessonType', 'verbose_name_plural': 'Типы уроков'},
        ),
        migrations.AlterModelOptions(
            name='studentsubject',
            options={'verbose_name': 'StudentSubject', 'verbose_name_plural': 'Ученик–предмет'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teachergrade',
            options={'verbose_name': 'TeacherGrade', 'verbose_name_plural': 'Учитель–класс'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'TeacherSubject', 'verbose_name_plural': 'Учитель–предмет'},
        ),
        migrations.AlterModelOptions(
            name='weeklynorm',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'WeeklyNorm', 'verbose_name_plural': 'Недельные нормы'},
        ),
    ]
