# Generated by Django 5.2.4 on 2025-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_academicyear_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
