# Generated by Django 5.2.4 on 2025-08-04 08:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_academicyear_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('official', 'Официальный выходной'), ('custom', 'Особый день')], default='official', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2005, 9, 1)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
        ),
    ]
