# Generated by Django 5.2.7 on 2025-10-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_holiday_academicyear_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], unique=True, verbose_name='Ступень (номер класса)')),
            ],
            options={
                'verbose_name': 'Ступень',
                'verbose_name_plural': 'Ступени',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Параллель')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Параллель',
                'verbose_name_plural': 'Параллели',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя класса'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.gradelevel', verbose_name='Ступень'),
        ),
        migrations.AddField(
            model_name='grade',
            name='parallel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.parallel', verbose_name='Параллель'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('level__isnull', False), ('parallel__isnull', False)), fields=('level', 'parallel'), name='uniq_grade_level_parallel'),
        ),
    ]
