# Generated by Django 5.2.3 on 2025-07-03 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reallesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='templatelesson',
            name='end_time',
        ),
        migrations.AddField(
            model_name='reallesson',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reallesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='templatelesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='reallesson',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
