# Generated by Django 5.2.3 on 2025-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_ktpsection_alter_reallesson_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ktpentry',
            name='date',
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='lesson_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='planned_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='type',
            field=models.CharField(choices=[('lesson', 'Урок'), ('course', 'Курс')], default='lesson', max_length=10),
        ),
        migrations.AddField(
            model_name='ktpsection',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
