# Generated by Django 5.2.4 on 2025-07-10 08:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_ktpentry_date_ktpentry_actual_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktpentry',
            name='template_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.templatelesson'),
        ),
        migrations.AddField(
            model_name='templateweek',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 8, 57, 34, 1032, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateweek',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
