# Generated by Django 5.2.4 on 2025-07-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_ktpentry_template_lesson_templateweek_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktptemplate',
            name='last_template_week_used',
            field=models.ForeignKey(blank=True, help_text='Шаблон недели, по которому последний раз были распределены даты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.templateweek'),
        ),
    ]
