# Generated by Django 5.2.4 on 2025-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_templateweekdraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklynorm',
            options={'ordering': ['grade', 'subject']},
        ),
        migrations.AddField(
            model_name='weeklynorm',
            name='courses_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Самостоятельных занятий (курсов)'),
        ),
        migrations.AddField(
            model_name='weeklynorm',
            name='lessons_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Уроков с учителем'),
        ),
        migrations.AlterField(
            model_name='weeklynorm',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(help_text='Всего часов в неделю по предмету'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklynorm',
            unique_together={('grade', 'subject')},
        ),
    ]
