# Generated by Django 5.2.4 on 2025-07-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_weeklynorm_options_weeklynorm_courses_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelesson',
            name='template_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.templateweek'),
        ),
    ]
