# Generated by Django 5.2.4 on 2025-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_templatelesson_template_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelesson',
            name='type',
            field=models.CharField(choices=[('lesson', 'Урок'), ('course', 'Курс')], default='lesson', help_text='Тип занятия: lesson — с учителем, course — самостоятельное', max_length=10),
        ),
    ]
