# Generated by Django 5.2.4 on 2025-07-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_templatelesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateweekdraft',
            name='base_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.templateweek'),
        ),
    ]
