# Generated by Django 5.2.4 on 2025-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_templateweekdraft_base_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('counts_towards_norm', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='templatelesson',
            name='type',
            field=models.CharField(default='lesson', max_length=20),
        ),
    ]
