# Generated by Django 5.2.4 on 2025-07-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_lessontype_alter_templatelesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelesson',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.lessontype'),
        ),
    ]
