version: "3.9"

networks:
  cedar_internal:
    driver: bridge
    internal: true

volumes:
  pgdata_beta:
  pgdata_prod:

services:
  # ---------- API (beta) ----------
  api-beta:
    container_name: cedar-api-beta
    build:
      context: ../..
      dockerfile: deploy/compose/Dockerfile.api
    env_file:
      - .env.beta
    depends_on:
      - pg-beta
    networks:
      - cedar_internal
    ports:
      - "127.0.0.1:5201:8000"   # Gunicorn внутри контейнера слушает :8000
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }
    command: >
      bash -lc "python manage.py collectstatic --noinput &&
                python manage.py migrate &&
                gunicorn config.wsgi:application -c gunicorn.conf.py"

  pg-beta:
    container_name: cedar-pg-beta
    image: postgres:15
    env_file:
      - .env.beta
    networks:
      - cedar_internal
    volumes:
      - pgdata_beta:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }

  # ---------- API (prod) ----------
  api-prod:
    container_name: cedar-api-prod
    build:
      context: ../..
      dockerfile: deploy/compose/Dockerfile.api
    env_file:
      - .env.prod
    depends_on:
      - pg-prod
    networks:
      - cedar_internal
    ports:
      - "127.0.0.1:5301:8000"
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }
    command: >
      bash -lc "python manage.py collectstatic --noinput &&
                python manage.py migrate &&
                gunicorn config.wsgi:application -c gunicorn.conf.py"

  pg-prod:
    container_name: cedar-pg-prod
    image: postgres:15
    env_file:
      - .env.prod
    networks:
      - cedar_internal
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }

  # ---------- FRONT (beta) ----------
  front-beta:
    container_name: cedar-front-beta
    build:
      context: ../..
    # Dockerfile.front в корне compose (см. ниже)
      dockerfile: deploy/compose/Dockerfile.front
    env_file:
      - .env.front-beta
    networks:
      - cedar_internal
    ports:
      - "127.0.0.1:5101:80"
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }
