# Generated by Django 5.2.4 on 2025-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='individual_subjects_enabled',
            field=models.BooleanField(default=False, help_text='Включить для ученика возможность индивидуального выбора предметов, иначе — все предметы наследуются от класса', verbose_name='Индивидуальный выбор предметов'),
        ),
        migrations.DeleteModel(
            name='UserGrade',
        ),
        migrations.DeleteModel(
            name='UserSubject',
        ),
    ]
