# Generated by Django 5.2.5 on 2025-09-03 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('relation', models.CharField(blank=True, help_text='Тип связи (мама/папа/опекун и т.п., опционально)', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(help_text='Ребёнок/ученик (роль: STUDENT)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Родитель (роль: PARENT)', on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь родитель-ребёнок',
                'verbose_name_plural': 'Связи родитель-ребёнок',
                'indexes': [models.Index(fields=['parent', 'is_active'], name='users_paren_parent__5229a9_idx'), models.Index(fields=['child', 'is_active'], name='users_paren_child_i_005209_idx')],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
