# Generated by Django 5.2.7 on 2025-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parentchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('DIRECTOR', 'Директор'), ('HEAD_TEACHER', 'Завуч'), ('METHODIST', 'Методист'), ('AUDITOR', 'Аудитор'), ('TEACHER', 'Учитель'), ('PARENT', 'Родитель'), ('STUDENT', 'Ученик')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('DIRECTOR', 'Директор'), ('HEAD_TEACHER', 'Завуч'), ('METHODIST', 'Методист'), ('AUDITOR', 'Аудитор'), ('TEACHER', 'Учитель'), ('PARENT', 'Родитель'), ('STUDENT', 'Ученик')], default='STUDENT', max_length=20),
        ),
    ]
