# Generated by Django 5.2.4 on 2025-07-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ktp', '0001_initial'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktpentry',
            name='template_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.templatelesson'),
        ),
        migrations.AddField(
            model_name='ktpentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ktp.ktpsection'),
        ),
        migrations.AddField(
            model_name='ktptemplate',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='ktptemplate',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktp_templates', to='core.grade'),
        ),
        migrations.AddField(
            model_name='ktptemplate',
            name='last_template_week_used',
            field=models.ForeignKey(blank=True, help_text='Шаблон недели, по которому последний раз были распределены даты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.templateweek'),
        ),
        migrations.AddField(
            model_name='ktptemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktp_templates', to='core.subject'),
        ),
        migrations.AddField(
            model_name='ktpsection',
            name='ktp_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ktp.ktptemplate'),
        ),
    ]
